services:
    go-irr:
        image: ghcr.io/jouandeag/go-irr:latest
        ports:
            - "8080:8080"
        environment:
            - SOURCES=AFRINIC,APNIC,ARIN,LACNIC,RIPE,RPKI
            - ALLOW_SOURCE_OVERRIDE=false
